name: First Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Step 1 complete!"
      - name: Step 2
        run: echo "Step 2 complete!"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Cowsay Action
        uses: peter-evans/cowsay@v1
        with:
          message: "Ready for prod-shit it!"
          color: magenta